# Generated by Django 3.0.3 on 2020-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conviction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARREST_BORO', models.TextField()),
                ('ARREST_PRECINCT', models.TextField()),
                ('JURISDICTION_CODE', models.TextField()),
                ('LONGITUDE', models.TextField()),
                ('AGE_GROUP', models.TextField()),
                ('PERP_SEX', models.TextField()),
                ('PERP_RACE', models.TextField()),
                ('WEEKDAY', models.TextField()),
                ('DRUG_RELATED', models.TextField()),
            ],
        ),
    ]
